# python -m huggingface_to_flat_tokens --config-name=c4_en max_tokens=100_000_000 +output=/your/path/to/c4_en_llama_flat_tokens
dataset: wikitext
variant: wikitext-103-v1
tokenizer: wikitext # may require huggingface-cli login
write_buffer_size_in_sequences: 65536
flat_tokens_config:
  tokens_chunk_size: 4194304
  seq_starts_chunk_size: 1048576
